# Generated by Django 6.0.2 on 2026-03-24 16:48

import core.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaGeoespacial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre de la capa')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('tipo_archivo', models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('SHAPE', 'Shapefile (.zip)'), ('GEOTIFF', 'GeoTIFF (.tiff)')], db_index=True, max_length=10, verbose_name='tipo de archivo')),
                ('archivo_original', models.FileField(help_text='Archivo tal como lo subió el investigador.', upload_to=core.models.capa_upload_path, verbose_name='archivo original')),
                ('tamano_bytes', models.BigIntegerField(default=0, verbose_name='tamaño en bytes')),
                ('checksum_md5', models.CharField(blank=True, max_length=32)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('ERROR', 'Error de validación'), ('PROCESANDO', 'Procesando ETL')], db_index=True, default='PENDIENTE', max_length=15, verbose_name='estado de validación')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('sistema_coordenadas', models.CharField(blank=True, help_text='Ej: EPSG:4326, EPSG:32614', max_length=50, verbose_name='sistema de coordenadas (EPSG)')),
                ('tipo_geometria', models.CharField(blank=True, choices=[('PUNTO', 'Puntos'), ('LINEA', 'Líneas'), ('POLIGONO', 'Polígonos'), ('RASTER', 'Ráster'), ('MIXTO', 'Mixto')], db_index=True, max_length=10, verbose_name='tipo de geometría')),
                ('wkb_geometria', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='Geometría completa almacenada en PostGIS para consultas espaciales.', null=True, srid=4326, verbose_name='geometría (PostGIS)')),
                ('geojson_path', models.CharField(blank=True, help_text='Ruta relativa al archivo GeoJSON generado por el ETL para Leaflet.', max_length=500, verbose_name='ruta GeoJSON optimizado')),
                ('num_features', models.PositiveIntegerField(default=0, verbose_name='número de features')),
                ('raster_path', models.CharField(blank=True, max_length=500, verbose_name='ruta GeoTIFF optimizado (COG)')),
                ('raster_bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='bounding box del ráster')),
                ('raster_banda_min', models.FloatField(blank=True, null=True)),
                ('raster_banda_max', models.FloatField(blank=True, null=True)),
                ('columnas_schema', models.JSONField(blank=True, default=dict, help_text="{'col_name': 'dtype', ...} detectado durante validación.", verbose_name='esquema de columnas')),
                ('columna_lat', models.CharField(blank=True, max_length=100)),
                ('columna_lon', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'capa geoespacial',
                'verbose_name_plural': 'capas geoespaciales',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='correo electrónico')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='nombre de usuario')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('especialidad', models.CharField(blank=True, help_text='Área de investigación (solo perfil Investigador).', max_length=200, verbose_name='especialidad')),
                ('rol', models.CharField(choices=[('INVESTIGADOR', 'Investigador'), ('NORMAL', 'Usuario Normal'), ('ADMIN', 'Administrador')], db_index=True, default='NORMAL', max_length=20, verbose_name='rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.avatar_upload_path, verbose_name='foto de perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='último acceso')),
                ('token_recuperacion', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_recuperacion_exp', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AtributoTabular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indice_original', models.PositiveIntegerField(help_text='Número de fila en el archivo fuente para trazabilidad.', verbose_name='índice fila original')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('punto', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('datos', models.JSONField(default=dict, help_text="Atributos del feature: {'especie': 'X', 'fecha': '...', ...}", verbose_name='datos del feature')),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atributos_editados', to=settings.AUTH_USER_MODEL)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='core.capageoespacial')),
            ],
            options={
                'verbose_name': 'atributo tabular',
                'verbose_name_plural': 'atributos tabulares',
                'ordering': ['capa', 'indice_original'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_email', models.EmailField(blank=True, max_length=254)),
                ('usuario_username', models.CharField(blank=True, max_length=50)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('REGISTRO', 'Registro de usuario'), ('SUBIDA', 'Subida de archivo'), ('VALIDACION_OK', 'Validación exitosa'), ('VALIDACION_ERR', 'Error de validación'), ('EDICION_ATTR', 'Edición de atributos'), ('PUBLICACION', 'Publicación de proyecto'), ('DESPUBLICACION', 'Despublicación'), ('ELIMINACION', 'Eliminación de recurso'), ('EXPORTACION', 'Exportación de reporte'), ('MODERACION', 'Moderación por administrador'), ('CAMBIO_CONTRASENA', 'Cambio de contraseña'), ('RECUPERACION', 'Recuperación de contraseña')], db_index=True, max_length=25, verbose_name='acción')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='tipo de objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=36, verbose_name='ID del objeto')),
                ('ip_origen', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Contexto libre: nombre de archivo, mensaje de error, etc.', verbose_name='datos adicionales')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de auditoría',
                'verbose_name_plural': 'logs de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('categoria', models.CharField(choices=[('CLIMA', 'Clima'), ('FAUNA', 'Fauna'), ('AGUA', 'Agua / Hidrología'), ('SUELO', 'Suelo'), ('VEGETACION', 'Vegetación'), ('ATMOSFERA', 'Atmósfera'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='categoría')),
                ('visibilidad', models.CharField(choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Público')], db_index=True, default='PRIVADO', max_length=10, verbose_name='visibilidad')),
                ('etiquetas', models.JSONField(blank=True, default=list, verbose_name='etiquetas')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha inicio del estudio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha fin del estudio')),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Calculado automáticamente al procesar las capas.', null=True, srid=4326, verbose_name='bounding box')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='miniatura del dashboard')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado_en', models.DateTimeField(blank=True, null=True, verbose_name='publicado en')),
                ('investigador', models.ForeignKey(limit_choices_to={'rol': 'INVESTIGADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitado_en', models.DateTimeField(auto_now_add=True)),
                ('veces', models.PositiveIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_consultas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'historial de consulta',
                'verbose_name_plural': 'historial de consultas',
                'ordering': ['-visitado_en'],
            },
        ),
        migrations.CreateModel(
            name='ExportacionReporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG')], max_length=5, verbose_name='formato')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=core.models.reporte_upload_path, verbose_name='archivo generado')),
                ('bbox_exportado', models.JSONField(blank=True, default=dict, help_text="{'north': ..., 'south': ..., 'east': ..., 'west': ...}", verbose_name='bbox del mapa al exportar')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'exportación de reporte',
                'verbose_name_plural': 'exportaciones de reportes',
                'ordering': ['-generado_en'],
            },
        ),
        migrations.AddField(
            model_name='capageoespacial',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='core.proyecto'),
        ),
        migrations.CreateModel(
            name='VersionCapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_version', models.PositiveSmallIntegerField(default=1, verbose_name='número de versión')),
                ('archivo_version', models.FileField(upload_to='versiones/', verbose_name='archivo de esta versión')),
                ('nota_version', models.CharField(blank=True, max_length=500, verbose_name='nota de versión')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='core.capageoespacial')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'versión de capa',
                'verbose_name_plural': 'versiones de capas',
                'ordering': ['capa', '-numero_version'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['rol', 'is_active'], name='core_custom_rol_29be53_idx'),
        ),
        migrations.AddIndex(
            model_name='atributotabular',
            index=models.Index(fields=['capa', 'indice_original'], name='core_atribu_capa_id_4e3fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['accion', 'timestamp'], name='core_logaud_accion_9f4d14_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', 'timestamp'], name='core_logaud_usuario_0123c3_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['ip_origen', 'timestamp'], name='core_logaud_ip_orig_f1b188_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['objeto_tipo', 'objeto_id'], name='core_logaud_objeto__54ee81_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['visibilidad', 'categoria'], name='core_proyec_visibil_312031_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['investigador', 'visibilidad'], name='core_proyec_investi_6ce70b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historialconsulta',
            unique_together={('usuario', 'proyecto')},
        ),
        migrations.AddIndex(
            model_name='capageoespacial',
            index=models.Index(fields=['proyecto', 'estado_validacion'], name='core_capage_proyect_a402e3_idx'),
        ),
        migrations.AddIndex(
            model_name='capageoespacial',
            index=models.Index(fields=['tipo_archivo', 'tipo_geometria'], name='core_capage_tipo_ar_b61951_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='versioncapa',
            unique_together={('capa', 'numero_version')},
        ),
    ]
