# Generated by Django 6.0.2 on 2026-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_recuperacion',
            field=models.CharField(blank=True, db_index=True, max_length=96),
        ),
    ]
