# Generated by Django 6.0.2 on 2026-04-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_token_recuperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capageoespacial',
            name='tipo_archivo',
            field=models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('CSV', 'CSV (.csv)'), ('SHAPE', 'Shapefile (.zip)'), ('GEOTIFF', 'GeoTIFF (.tiff)')], db_index=True, max_length=10, verbose_name='tipo de archivo'),
        ),
    ]
